---
version: '2'
services:
  airman:
    build: .
    container_name: airman
    image: docker.io/nucleardreamer/airman
    network_mode: host
    # devices:
    #   - /dev/dri:/dev/dri
    volumes:
      - /run/udev:/run/udev
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/shm:/dev/shm
  watchtower:
    image: v2tec/watchtower:armhf-latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    # environment:
    #   REPO_USER: ${REPO_USER}
    #   REPO_PASS: ${REPO_PASS}
